[tool.towncrier]
name = 'elbe'
package = 'elbepack'
directory = 'newsfragments'
single_file = false
filename = 'docs/news/{project_date}-v{version}.rst'

[tool.pytest.ini_options]
python_files = [
    'test_*.py',
    '*_test.py',
    'contrib/check-deb-py-versions.py',
    'contrib/prepare-release.py',
]
filterwarnings = 'error'

[tool.mypy]
packages = [
  'elbepack',
  'elbevalidate',
]
ignore_missing_imports = true
python_version = '3.9'
